all:
    hosts:
        vps:
            ansible_host: "{{ lookup('ansible.builtin.env', 'VPS_IP') }}"
            ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    vars:
        username: "{{ lookup('ansible.builtin.env', 'USERNAME') }}"
        authorized_key: "{{ lookup('ansible.builtin.env', 'AUTHORIZED_KEYS') }}"
        ports:
            ssh: 22
            http: 80
            https: 443
