all:
    hosts:
        vps:
            ansible_host: "{{ lookup('ansible.builtin.env', 'VPS_IP') }}"
            ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    vars:
        users: 
            - name: "some user"
              sudo: true
            - name: "deployer"
              sudo: false
        ports:
            ssh: 22
            http: 80
            https: 443
