all:
    hosts:
        vps:
            ansible_host: "{{ lookup('ansible.builtin.env', 'VPS_IP') }}"
            ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    vars:
        users:
            - name: "{{ lookup('ansible.builtin.env', 'USER') }}"
              sudo: true
              authorized_keys: "{{ lookup('ansible.builtin.env', 'AUTHORIZED_KEYS_USER') }}"
            - name: "deployer"
              sudo: false
              authorized_keys: "{{ lookup('ansible.builtin.env', 'AUTHORIZED_KEYS_DEPLOYER') }}"
        ports:
            ssh: 22
            http: 80
            https: 443
