- name: Create user
  hosts: vps
  remote_user: root
  become: true
  tasks:
    - name: Run User role for every user defined
      ansible.builtin.include_role:
        name: user
      loop: "{{ users }}"
      loop_control:
        loop_var: user

- name: Server setup
  hosts: vps
  remote_user: "{{ username }}"
  become: true
  roles:
    - role: ssh
      tags:
        - ssh
    - role: ufw
      tags:
        - firewall
    - role: docker
      tags:
        - docker
