- name: Ensure the user exists
  ansible.builtin.user:
    name: "{{ user.name }}"
    state: present

- name: Create the .ssh directory
  ansible.builtin.file:
    path: "/home/{{ user.name }}/.ssh"
    state: directory
    owner: "{{ user.name }}"
    mode: '0700'

- name: Add the public keys to the authorized_keys file
  ansible.builtin.blockinfile:
    path: "/home/{{ user.name }}/.ssh/authorized_keys"
    block: "{{ user.authorized_keys }}"
    create: true
    owner: "{{ user.name }}"
    mode: '0600'
