- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: "Create user {{ username }}"
  ansible.builtin.user:
    name: "{{ username }}"
    groups:
      - sudo
      - docker
    system: true
    # default value is true might remove
    # createhome: true
    home: "/home/{{ username }}"

- name: "Password-less sudo for {{ username }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ username }}"
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
