- name: Create docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: "Create user {{ user.name }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups:
      - docker
    system: true

- name: "Create user {{ user.name }}"
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups:
      - sudo
    system: true
    append: true
  when: user.sudo

- name: "Password-less sudo for {{ user.name }}"
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: "^{{ user.name }}"
    line: "{{ user.name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "/usr/sbin/visudo -cf %s"
  when: user.sudo
