#  - name: Get openssh-server version
#    ansible.builtin.shell: 'set -o pipefail & ssh -V 2>&1 | sed -r "s/^OpenSSH_([0-9]+\.[0-9]+).*/\1/"'
#    register: ssh_version_raw
#    changed_when: false
#
#  - name: Set OpenSSH version as float
#    ansible.builtin.set_fact:
#      ssh_version: "{{ ssh_version_raw.stdout | float }}"

- name: Create ssh_config
  ansible.builtin.template:
    src: 'ssh_conf.j2'
    dest: '/etc/ssh/ssh_config'
    mode: '0644'
    owner: '{{ users[0].name }}'
    validate: 'ssh -f %s -G > /dev/null'
  notify: Restart ssh service
