- name: Get opensshd-server version
  ansible.builtin.shell: 'set -o pipefail & sshd -V 2>&1 | sed -r "s/^Openssh_([0-9]+\.[0-9]+).*/\1/"'
  register: sshd_version_raw
  changed_when: false

- name: Set Opensshd version as float
  ansible.builtin.set_fact:
    sshd_version: "{{ sshd_version_raw.stdout | float }}"

- name: Create sshd_config and set permissions to root/644
  ansible.builtin.template:
    src: 'sshd_conf.j2'
    dest: '/etc/ssh/sshd_config'
    mode: '0644'
    owner: '{{ users[0].name }}'
