name: deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15
    
      - run: cat /etc/alpine-release
        shell: alpine.sh {0}
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ansible and Ansible-lint
        run: |
          sudo apk update
          sudo apk add -y pipx
          pipx install ansible-core
          pipx install ansible-lint

      - name: Download Ansible community.general and ansible.posix libraries
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install ansible.posix
          sudo apk update && upgrade -y

      - name: Run ansible-lint
        run: |
          ansible-lint

      - name: Setup SSH Key
        with:
          vps_ip: ${{ secrets.VPS_IP }}
        uses: rafasmour/actions/.github/workflows/ssh.yml@main

      - name: Cache ssh key passphrase & Run Ansible Playbook
        env:
          AUTHORIZED_KEYS_USER: ${{ secrets.AUTHORIZED_KEYS_USER }}
          AUTHORIZED_KEYS_DEPLOYER: ${{ secrets.AUTHORIZED_KEYS_DEPLOYER }}
          SSH_PASSPHRASE: ${{ secrets.DEPLOY_SSH_PASSPHRASE }}
          USER: ${{ secrets.USER }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
            eval "$(ssh-agent -s)"
            echo "echo \"$SSH_PASSPHRASE\"" > ./askpass.sh
            chmod +x ./askpass.sh
            export SSH_ASKPASS=./askpass.sh
            export DISPLAY=:0
            setsid ssh-add /home/runner/.ssh/id_rsa < /dev/null
            ansible-playbook -i inventory.yml -vvv main.yml
