name: deploy

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Alpine
        uses: jirutka/setup-alpine@v1
        with:
          branch: "v3.15"
  
      - name: Verify Alpine Release
        run: cat /etc/alpine-release
        shell: alpine.sh {0}
        
      - uses: rafasmour/actions/.github/actions/ssh.yml@v1
        with:
          vps_ip: ${{ secrets.VPS_IP }}
        
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ansible and Ansible-lint
        run: |
          apk update
          apk add -y pipx
          pipx install ansible-core
          pipx install ansible-lint

      - name: Download Ansible community.general and ansible.posix libraries
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install ansible.posix
          apk update && upgrade -y

      - name: Run ansible-lint
        run: |
          ansible-lint

      

      
